name: Tests

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Check style
        run: |
          flake8 `find . -name "*.py"`

      - name: Run tests
        run: |
          python3 -m pytest tests/